times = {
    'Alemanha': 'Alemanha',
    'Alemania': 'Alemanha',
    'Amsterdã': 'Amsterdam',
    'Ámsterdam': 'Amsterdam',
    'Argentina': 'Argentina',
    'Aston': 'Aston',
    'Áustria': 'Austria',
    'Barcelona': 'Barcelona',
    'Bélgica': 'Belgica',
    'Benfica': 'Benfica',
    'Brasil': 'Brasil',
    'Brentford': 'Brentford',
    'Brighton': 'Brighton',
    'Burnley': 'Burnley',
    'Celtic': 'Celtic',
    'Chelsea': 'Chelsea',
    'City': 'City',
    'Colômbia': 'Colombia',
    'Croacia': 'Croacia',
    'Croácia': 'Croacia',
    'Dinamarca': 'Dinamarca',
    'Dortmund': 'Dortmund',
    'Escócia': 'Escocia',
    'Eslovaquia': 'Eslovaquia',
    'Eslováquia': 'Eslovaquia',
    'España': 'Espanha',
    'Espanha': 'Espanha',
    'Everton': 'Everton',
    'Finlandia': 'Finlandia',
    'Finlândia': 'Finlandia',
    'França': 'Franca',
    'Francia': 'Franca',
    'Hungria': 'Hungria',
    'Inglaterra': 'Inglaterra',
    'Islington': 'Islington',
    'Itália': 'Italia',
    'Leeds': 'Leeds',
    'Leicester': 'Leicester',
    'Liverpool': 'Liverpool',
    'Macedonia del Norte': 'Macedonia do Norte',
    'Macedônia do Norte': 'Macedonia do Norte',
    'Madrid': 'Madrid',
    'México': 'Mexico',
    'Milan': 'Milan',
    'Múnich': 'Munique',
    'Munique': 'Munique',
    'Newcastle': 'Newcastle',
    'Norwich': 'Norwich',
    'País de Gales': 'Pais de Gales',
    'Países Baixos': 'Paises Baixos',
    'Países Bajos': 'Paises Baixos',
    'Palace': 'Palace',
    'Paris': 'Paris',
    'París': 'Paris',
    'Polonia': 'Polonia',
    'Polônia': 'Polonia',
    'Porto': 'Porto',
    'Portugal': 'Portugal',
    'República Tcheca': 'Republica Tcheca',
    'Rome': 'Roma',
    'Rusia': 'Russia',
    'Rússia': 'Russia',
    'Southampton': 'Southampton',
    'Suécia': 'Suecia',
    'Suíça': 'Suica',
    'Tottenham': 'Tottenham',
    'Turin': 'Turin',
    'Turquia': 'Turquia',
    'Ucrânia': 'Ucrania',
    'United': 'United',
    'Uruguai': 'Uruguai',
    'Watford': 'Watford',
    'West Ham': 'West Ham',
    'Wolverhampton': 'Wolverhampton',
    'República Checa': 'Republica Tcheca',
    'Turquía': 'Turquia',
    'Escocia': 'Escocia',
    'Suiza': 'Suica',
    'Ucrania': 'Ucrania',
    'Colombia': 'Colombia',
    'Oporto': 'Porto',
    'Roma': 'Roma',
    'Milán': 'Milan',
    'Uruguay': 'Uruguai',
    'Turín': 'Turin',
    'Suecia': 'Suecia',
    'Austria': 'Austria',
    'Italia': 'Italia',
    'Gales': 'Pais de Gales',
    'Hungría': 'Hungria',
    'West ham': 'West Ham',
    'Wolverhampto': 'Wolverhampton',
    'Dormund': 'Dortmund',
}
